### ISSUE TITLE
Cannot connect to library in AD 22.6.1 

### ISSUE THREAD

**Issue by Mrelectricvideo** [issus/altium-library#101]
This I have tried many times in the last few days to access  altium-library but without success. Tried to ensure port 1433 was open in Netgear router and Windows 11 64 firewall but have given up and used a :80 version as new login and download to the git folder. Followed all the steps with ports, SQL app etc carefully but no luck. See error message as png.

String (user redacted) is:
Provider=SQLNCLI11.1;Persist Security Info=False;User ID=alib_*;Initial Catalog=altium_library;Data Source=db.altiumlibrary.com,80;Initial File Name="";Server SPN=""

I really want to use this resource. Does anyone have any thoughts please?
David
![Screenshot 2022-08-03 181951](https://user-images.githubusercontent.com/83813680/182670193-d9d4d23d-1be2-460e-be8b-2983e0cb0bfa.png)

**Comment by Mrelectricvideo** [comment]
A few reboots and it seems to work OK now. Odd but it was worth it.

**Comment by issus** [comment]
@tebbo123 I'm going to delete your comment because the screenshot has a password in it. You may also get this message if you have failed to login multi-times, the system will ban you for 24hrs if you do. Download a new DBLib and try again after a day.

**Comment by Z-ack-L** [comment]
> [@tebbo123](https://github.com/tebbo123) I'm going to delete your comment because the screenshot has a password in it. You may also get this message if you have failed to login multi-times, the system will ban you for 24hrs if you do. Download a new DBLib and try again after a day.

Hi.[@issus] Does “the system will ban you for 24hrs” mean banned from logging in? Or IP ban?

Recently I can't use this library because the network is behaving strangely. I can successfully connecting to the database once, then can't connect again. Moreover, ping server become unreachable after one successfully connect.

Tried again in a few days, same cycle. Can ping through and connect successfully once, then can't connect again and ping response unreachable.
